### ISSUE TITLE
command 'find-it-faster.findFiles' not found with 0.0.37

### ISSUE THREAD

**Issue by oriolgual** [tomrijndorp/vscode-finditfaster#101]
If I upgrade to the latest version I get this error when trying to use the extension (Cmd + Shift + J), everything works OK with 0.0.36. Do I need to change something or is it a bug?

**Comment by tomrijndorp** [comment]
Thanks for reporting! I can confirm this is the case. Looking into why this might be happening.

**Comment by tomrijndorp** [comment]
Alright, version `0.0.38` is now up and should have resolved this. Please let me know if there's somehow still an issue. Thanks again.

**Comment by oriolgual** [comment]
Works OK now, thanks!
