### ISSUE TITLE
`Search Within Files` `rg` options

### ISSUE THREAD

**Issue by jfrerich** [tomrijndorp/vscode-finditfaster#11]
Frist off, thanks for this extension!  I found it while trying to convert my Vim setup to vscode.

Is there a way to modify the search within files `rg` command?  I would like to modify the output to remove the portion of the path that leads up to the project folder. 

This is in vscode
<img src="https://user-images.githubusercontent.com/7575921/142032393-303e15bb-a67f-4723-a9bd-7dbe6c4966d2.png"/>

In vim, I have modified the results of rg to omit the path preceding the project directory
<img src="https://user-images.githubusercontent.com/7575921/142032646-d540ff95-2d22-4851-bd84-bd0d328d4c39.png"/>

**Comment by tomrijndorp** [comment]
Hi Jason, thank you for reporting! The reason I do this is that the extension supports multiple search folders. That is, if you run the `list search locations` command, you'll see that depending on a number of factors, the extension will search one or more folders. Currently, having one active search folder is simply treated in the same way as multiple folders, and for this to work I need to pass the full paths (or figure out some common path, which is not super intuitive if not presented well).

That said, I can make an exception for the "just-one-search-path" case, I think that would provide slightly nicer UX and might be relevant in your case (I don't know how many paths are being searched in your case). I'll see if I can squeeze this in soon :)

**Comment by jfrerich** [comment]
The output of my `list search locations` comand includes which would match your `just-one-search-path` case.  This woule be very cool to see :) Thanks for the response!

```
Paths added because they're defined in the workspace:
- /Users/xxxxx/go/src/github.com/mattermost/mattermost-mobile
```

**Comment by tomrijndorp** [comment]
Hi Jason, it was a little trickier than I expected (the deeper I need to get into bash, the more differences between versions and Mac/Linux show up...) but if you update to `0.0.15` you should now see that the paths are relative when you have only one directory being searched! Please let me know if it somehow doesn't work as expected for you :)

**Comment by jfrerich** [comment]
This is great! Thanks and I hope others like the update also :) 
![image](https://user-images.githubusercontent.com/7575921/144260572-34ebd9b8-33e9-4120-b983-8e4d33a77adf.png)
