### ISSUE TITLE
Can't open files when there are multiple folders in workspace

### ISSUE THREAD

**Issue by bisho** [tomrijndorp/vscode-finditfaster#12]
When I have several folders in the workspace (File->Add folder to workspace), the extension still searches correctly in the terminal, but it can't open the selected file when pressing enter. Strangely enough, clicking on the path+line link in the terminal works as intended.

**Comment by bisho** [comment]
I'm running on OSX VS Code Version: 1.63.2, FindItFaster v0.0.16.

The list folders command correctly displays all folders.

This happens when using "find within files". The path is show relative to one of the working dirs. When using find files, paths show absolute path and they work.

**Comment by tomrijndorp** [comment]
Hi bisho, thanks for reporting! I've played around with this a bit and can't reproduce. You definitely shouldn't be seeing a relative path in there when you have a multi-root workspace (thanks for mentioning that!), so that's a bug indeed. Would you mind sharing:
* the output of your workspace configuration; that is, any (anonymized / redacted) paths under `folders`? I'd like to understand if maybe there's something there that stands out to me like spaces, relative paths, etc.
* if you have any paths added to `find-it-faster.general.additionalSearchLocations` that would be good to know.
* if you could also share the (anonymized) output of the "list search locations" command, that would be super helpful. 

Thanks so much!

**Comment by bisho** [comment]
I tried to repro, but now the "find within files" doesn't show one of the folders added.

* I didn't have any paths in `find-it-faster.general.additionalSearchLocations`
* The list search locations produces:
```
----------
The following files are on your search path:
- /Users/bisho/Work/coding/test/project_a
- /Users/bisho/Work/coding/test/project_b

Paths added because they're the working directory:
- <none>
Paths added because they're defined in the workspace:
- /Users/bisho/Work/coding/test/project_a
- /Users/bisho/Work/coding/test/project_b
Paths added because they're the specified in the settings:
- <none>
----------
```

Repro steps:
* I have created two project folders, with foo and bar files that contain foo and bar:
```
./project_b
./project_b/b
./project_b/b/foo
./project_b/b/bar
./project_a
./project_a/a
./project_a/a/foo
./project_a/a/bar
```
* I open project_a folder in vscode.
* I add project_b folder to workspace
* Search files by name shows both folders.
* Search within files only shows files in project_a

If I add them in different order, first open folder project_b, then add folder project_a, then search within files only shows from project_b.

**Comment by bisho** [comment]
More info on this. When I have a single folder open, both search files / search within files display relative paths. As soon as another folder is added to the workspace, the search files correctly switches to absolute paths, but search within files does not...

**Comment by bisho** [comment]
Changed `find_within_files.sh` to run with `-x` for debugging purposes:

The issue seems to be that `. shared.sh` fails, pwd is not the current folder.

```
::: Terminal allocated for FindItFaster. Do not use. ::: /Users/bisho/.vscode/extensions/tomrijndorp.find-it-faster-0.0.16/find_within_files.sh  '/Users/bisho/Work/coding/test/project_a' '/Users/bisho/Work/coding/test/project_b'
+ set -uo pipefail
+ . shared.sh
/Users/bisho/.vscode/extensions/tomrijndorp.find-it-faster-0.0.16/find_within_files.sh: line 4: shared.sh: No such file or directory
```

That causes `array_join` to fail later.

**Comment by tomrijndorp** [comment]
Hi bisho, this is awesome, thanks for looking into it in so much detail! I'm having a bit of a crazy week this week, but next week I should have some time to look into it address this. Thank you!

**Comment by bisho** [comment]
Note I suggested a PR https://github.com/tomrijndorp/vscode-finditfaster/pull/13 to fix this :) It is working for me locally!

**Comment by tomrijndorp** [comment]
Hah, that's a great catch! I now realize that the reason `shared.sh` would load for me was that generally when I'm working on the extension, the folder that contains `shared.sh` is my PWD 🤦. I somehow didn't catch this when I was testing my latest release, so thanks!

I think your solution makes sense, but I'm going to have to do some testing before I can merge. For one, `realpath` is not available by default on Mac OS. Thanks for your patience :)

**Comment by tomrijndorp** [comment]
Alright, version 0.0.17 is now released! Thanks again, and do please let me know if things don't work as you'd expect!

**Comment by bisho** [comment]
Thanks to you!!! I can't live without this extension :)
