### ISSUE TITLE
Search hidden/exclude files

### ISSUE THREAD

**Issue by janosimas** [tomrijndorp/vscode-finditfaster#14]
Great extension, thanks for making it!

I want to search in files at hidden and excluded folders. Is it possible to do this with the extension?

I'm not sure if related but if I set
```
"find-it-faster.general.useWorkspaceSearchExcludes": false,
```
I get a `Command failed` error, unfortunately I cannot see the full error to check the options.

**Comment by tomrijndorp** [comment]
Hi @janosimas, glad to hear! I think I might have found the issue; aside from the `search.excludes` added from the workspace, the extension (really it's `ripgrep`) is configured such that it also ignores any entries from your `.gitignore`. Could you confirm the file your were looking for is indeed filtered out through your `.gitignore`?

**Comment by janosimas** [comment]
Yes, that's the case.
I'd like to have the option to add the flag `-u` to ripgrep.

**Comment by tomrijndorp** [comment]
Alright, that's _basically_ what I implemented now. In version `0.0.18` (available now), you'll find the additional option to `Use `.gitignore` entries (if present) to limit search paths` (`find-it-faster.general.useGitIgnoreExcludes`) in the preferences which is on by default. So turning it off should get you the behavior you need!

**Comment by janosimas** [comment]
It's working like a charm.
Thanks
