### ISSUE TITLE
Feature Request: find file with type pre-filtering

### ISSUE THREAD

**Issue by prime31** [tomrijndorp/vscode-finditfaster#15]
Great work on this extension! It let me throw my personal messy extension away. There is one small thing I would love to see: find file with type pre-filtering.

**Comment by tomrijndorp** [comment]
Thanks for the compliment! It's a little inconsistent that I didn't create an option for it. I think it's a sensible thing to add and I'll add it next time I go in to fix a bug. Thanks for reporting!

**Comment by tomrijndorp** [comment]
Hey @prime31, as of 0.0.19, you can now use pre-filtering on searching files. Though I didn't create a default key binding for it, it's exposed in the command palette. Thanks again for the suggestion!

**Comment by prime31** [comment]
Awesome! Thanks for the heads up!
