### ISSUE TITLE
Add cycle option to fzf

### ISSUE THREAD

**Issue by shlomocarmeter** [tomrijndorp/vscode-finditfaster#16]
Hi,

First I'd like to say that this is a great plugin!
Could you please add the switch --cycle on line 58 of find_files.sh ?

Thanks

**Comment by tomrijndorp** [comment]
Thanks! I'll add the switch (or maybe a configuration option to pass additional flags such that everybody can tailor this command as they see fit) the next time I release an update!

**Comment by shlomocarmeter** [comment]
Thank you!

**Comment by tomrijndorp** [comment]
Hey @shlomocarmeter, as of 0.0.19, this option is now the default. Thanks for the suggestion!

**Comment by shlomocarmeter** [comment]
@tomrijndorp Thanks!
