### ISSUE TITLE
Feature request: Ability to change the preview bat theme

### ISSUE THREAD

**Issue by mariush2** [tomrijndorp/vscode-finditfaster#17]
Hi! Started using this tool and it makes changing files and searching in vscode x10 better.

I was wondering if it is possible to expose a setting called "BAT_THEME" or something similar, either that or maybe it is possible to piggy back of the $BAT_THEME shell variable that bat uses itself

**Comment by tomrijndorp** [comment]
Hi Marius, thanks for the kind words! Exposing the theme through settings and/or env var should be easy. I have a couple simple feature requests lined up; I'll try to push an update in the next week or so and let you know here when it happens.

Thanks for the suggestion!

**Comment by mariush2** [comment]
Great, thanks for the quick response!

**Comment by tomrijndorp** [comment]
Hey @mariush2, as of 0.0.19, you can now set [`find-it-faster.general.batTheme`](https://github.com/tomrijndorp/vscode-finditfaster/blob/release/package.json#L147-L151) to the theme you want to use. It's exposed in the UI. Thanks for the suggestion!
