### ISSUE TITLE
Options to search in other directory

### ISSUE THREAD

**Issue by albert-ying** [tomrijndorp/vscode-finditfaster#19]
Hi, thank you for this amazing plugin!

The current version only supports searching in the current working directory, but sometimes I want to search the files outside the project folder. Is it possible to implement an pop-up window (like the one when you press cmd+o) to confirm which directory I would like to search?

**Comment by tomrijndorp** [comment]
Hi @albert-ying, thanks for the kind words and the suggestion! My intuition is that doing this through a popup might be the workflow that suits most folks' work flow best, though. Some existing options I can think of that might suit your need:

Are you familiar with VS Code's [workspaces](https://code.visualstudio.com/docs/editor/workspaces) and also [multi-root workspaces](https://code.visualstudio.com/docs/editor/workspaces#_multiroot-workspaces)? If you have a workspace open, the extension will by default search all those folders. And if somehow, that's not good enough, it is also possible to specify additional locations specific to the extension by setting `find-it-faster.general.additionalSearchLocations` in your preferences. You can always get a summary of which directories are currently being searched by the extension by running the "Find It Faster: list search locations" command.

Please let me know if one of those existing paradigms work for you!
