### ISSUE TITLE
Unable to open files from terminal window

### ISSUE THREAD

**Issue by ObieMunoz** [tomrijndorp/vscode-finditfaster#23]
**Describe the bug**
Unable to open files from terminal window.

```
EXCEPTION: A parameter cannot be found that matches parameter name 'Path'.
at <ScriptBlock>, ...\.vscode\extensions\tomrijndorp.find-it-faster-0.0.21\find_within_files.ps1: line 115
at <ScriptBlock>, <No file>: line 1
Out-File : A parameter cannot be found that matches parameter name 'Path'.
At ...\.vscode\extensions\tomrijndorp.find-it-faster-0.0.21\find_within_files.ps1:115 char:75
+ ... Path "$SINGLE_DIR_ROOT" -ChildPath "$result" | Out-File -Path "$Env:C ...
+                                                             ~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Out-File], ParameterBindingException
    + FullyQualifiedErrorId : NamedParameterNotFound,Microsoft.PowerShell.Commands.OutFileCommand
```

**To Reproduce**
1. `ctrl+shift+j` or `ctrl+shift+u`
2. Navigate the file tree using keyboard
3. Press `enter` on a file

**Expected behavior**
File opens in VS Code when selected

**Screenshots**
![image](https://user-images.githubusercontent.com/5696449/218150898-8d1dd677-42d3-41e6-af96-d75cbccf6147.png)
![image](https://user-images.githubusercontent.com/5696449/218151086-4346313e-87fe-4bef-8708-e2dae85f98cf.png)

**Desktop:**
 - OS: MS Windows 10 Enterprise
 - Version 10.0.19045
 - Terminal: PowerShell
   - PSVersion 5.1.19041.2364
 - rg, fzf, and bat all are confirmed to work independently.

**Comment by ObieMunoz** [comment]
Any thoughts on this, @tomrijndorp?

**Comment by ObieMunoz** [comment]
> 

No problem. Thanks @tomrijndorp, hopefully @ihdavids can take a look when there's time.

I was going to try and patch it myself but my fix was very janky and didn't work the best. I haven't done a ton of Powershell scripting.

**Comment by ihdavids** [comment]
I will certainly take a look as I can.
I

**Comment by tomrijndorp** [comment]
This should be fixed now -- thanks @Coombszy! If there's somehow an issue, please let us know :)
