### ISSUE TITLE
find no effect

### ISSUE THREAD

**Issue by keeYuc** [tomrijndorp/vscode-finditfaster#24]
OS: macOS 13.2.1 22D68 arm64

When I press the keyboard, 
following appears
//
bash
export PS1="::: Terminal allocated for FindItFaster. Do not use. ::: "; clear
/Users/keeyu/.vscode/extensions/tomrijndorp.find-it-faster-0.0.21/find_within_files.sh  '/Users/keeyu/code/company/probation'
//
But I directly execute the following command. It works very well
//
/Users/keeyu/.vscode/extensions/tomrijndorp.find-it-faster-0.0.21/find_within_files.sh  '/Users/keeyu/code/company/probation'
//

**Comment by tomrijndorp** [comment]
Hi @keeYuc,

This is a known issue. I have no means of actually confirming the state of the shell, and in some conditions this happens, usually fairly sporadically. I unfortunately have no perfect fix though. That said, if you terminate the shell session (using the thrash can icon in the top right corner of the terminal) and activate the extension again, things should work as expected again. Let me know if this works for you!

**Comment by keeYuc** [comment]
> Hi @keeYuc,
> 
> This is a known issue. I have no means of actually confirming the state of the shell, and in some conditions this happens, usually fairly sporadically. I unfortunately have no perfect fix though. That said, if you terminate the shell session (using the thrash can icon in the top right corner of the terminal) and activate the extension again, things should work as expected again. Let me know if this works for you!

Thank you very much for your reply
