### ISSUE TITLE
Provide a way to specify custom rg/fzf/bat executable or additional directories to search them for

### ISSUE THREAD

**Issue by astrolemonade** [tomrijndorp/vscode-finditfaster#33]
Provide a way to specify custom rg/fzf/bat executable or additional directories to search them for.
I have all the executables in directories that are part of the PATH variable. For some reason, vscode does not start with running also the .bashrc.

**Comment by tomrijndorp** [comment]
Hi @astrolemonade, have you tried setting `PATH` in VS Code's preferences? This should solve your problem. Here's a [stackoverflow post](https://stackoverflow.com/a/45637716/888916) that explains how to do it.

If that doesn't work, you could also consider symlinking the binaries to a location that is on VS Code's `PATH`.

I hope that solves your issue!
