### ISSUE TITLE
Add a command to search using the previous search query

### ISSUE THREAD

**Issue by AlexanderArvidsson** [tomrijndorp/vscode-finditfaster#34]
Hi! I love this extension, use it every day. 🥇 

Something I've noticed I do a lot is going through search results one by one, editing as I go. 
It would be great if there's a way to open the search prompt using the same search query as I ended on the last time I ran the command.

Either that, or add a shortcut when searching that prefills the last searched result (or maybe history?). Maybe this option would be more part of FZF (maybe it already exists, I can't find it).

If you got a better way, please tell me!

**Comment by tomrijndorp** [comment]
Hi @AlexanderArvidsson, great to hear you like the extension! This is indeed not a feature right now, but I might have a suggestion that is an equally nice (or perhaps better) workflow: did you know that it's possible to select multiple lines using `tab`? This will open all selected files.

**Comment by AlexanderArvidsson** [comment]
@tomrijndorp Hi, I tried the tab option but it does not seem to do anything on my computer. Regardless, the use case I have is not to open a bunch of files, it's to go through a file one-by-one and do code changes in multiple files in order.
This is very important when refactoring, and I don't think the workflow you describe fits in here since I am not looking to open all files at once (that's not very good for ZEN).

Thanks for the info though! If I can get `tab` to work, that could be useful as well for other cases!

**Comment by tomrijndorp** [comment]
Got it -- thanks for explaining :)I was hoping that `fzf`would have built in support for this, but it appears that it doesn't. I'm not sure if this can be tackled in a neat way. By the way, there is one more related feature in the extension: if you have an active text selection, that selection will be used to prepopulate the query field.

**Comment by AlexanderArvidsson** [comment]
> Got it -- thanks for explaining :)I was hoping that `fzf`would have built in support for this, but it appears that it doesn't. I'm not sure if this can be tackled in a neat way. By the way, there is one more related feature in the extension: if you have an active text selection, that selection will be used to prepopulate the query field.

Neat feature! I think I'll definitely make use of that, since I usually just copy and paste into the prompt.
I just had to change my bindings to make the command work in Vim's visual selection mode, and it works fine!
Thanks for the tip, it'll definitely speed things up! :)

If you ever get around to the previous query feature, hit me up! Perhaps I'll take a shot at it myself in the coming weeks when I find time.

**Comment by tomrijndorp** [comment]
Thanks -- will do!
