### ISSUE TITLE
Massive typescript performance degredation with extension enabled

### ISSUE THREAD

**Issue by evelant** [tomrijndorp/vscode-finditfaster#35]
Type: <b>Bug</b>

Enable extension, attempt typescript auto complete in a large project, observe it fail completely or become extremely slow. Disable extension and problem disappears.

Extension version: 0.0.21
VS Code version: Code 1.79.2 (695af097c7bd098fbf017ce3ac85e09bbc5dda06, 2023-06-14T08:58:33.551Z)
OS version: Darwin arm64 22.5.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Pro (10 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|34, 28, 21|
|Memory (System)|16.00GB (0.08GB free)|
|Process Argv||
|Screen Reader|yes|
|VM|0%|
</details>

**Comment by tomrijndorp** [comment]
Thanks for reporting. Unfortunately I don't know how to respond to this. If this extension is hurting autocomplete performance in Typescript projects, my first thought is that it seems to be a VS Code issue? This extension is not configured to trigger on autocomplete (or do anything with respect to Typescript-based projects for that matter), so I don't know where to start attempting to reproduce this.
