### ISSUE TITLE
Files do not open again in Windows? 

### ISSUE THREAD

**Issue by ch0pex** [tomrijndorp/vscode-finditfaster#38]
I can't open any file in Windows, pressing Enter does nothing. Its maybe my problem?

**Comment by tomrijndorp** [comment]
Hi @ch0pex, were you using the extension before and did it work? If so, #23 which I merged yesterday may have broken it. Please let me know, as I don't have a Windows machine myself for testing. Thank you!

**Comment by ch0pex** [comment]
Just downloaded today, very nice job btw love the extension!. I wrote "again" just because I saw you've already fixed a similar bug. In my case there is no error message after pressing enter it just close the terminal and open nothing. Meanwhile I can use it with wsl. :)

**Comment by tomrijndorp** [comment]
Sorry I can't be of more help, I don't have a Windows machine to perform testing so I rely on community contributions to get that to work smoothly :)

**Comment by ch0pex** [comment]
It seems to be an issue with the canaryFile encoding. Adding "-Encoding UTF8" to Out-File parameters fixed it #39

**Comment by tomrijndorp** [comment]
#39 will be included in release `0.0.25` which is being released now. Thanks again!
