### ISSUE TITLE
terminal stays open after search is selected

### ISSUE THREAD

**Issue by AdamBD** [tomrijndorp/vscode-finditfaster#40]
After opening the search fucntion and selecting a result, when you open the terminal panel again in vscode it opens the finditfaster terminal. This is annoying because I want to go back to using an active terminal and need to open a new panel for this.

Is there anyway around this?

**Comment by M-Sukhostavets** [comment]
Hi, I also want to add this feature. I have ideas on how this could work, I'd be happy to work on it

Idea is to save `vscode.window.activeTerminal` when creating/opening terminal and `.show()` on success. Hiding terminal would be tricky, but making disposable event listener should help.

@tomrijndorp what do you think about that?

**Comment by tomrijndorp** [comment]
Alright, so this is now in, thanks @MykhailoSukhostavets! There are unfortunately some limitations in VS Code's API, which means the following aspects cannot be fixed as of now (unless I'm wrong)
- switching back to other panels (e.g. "debug output")
- hiding the panel when there was a previously active terminal, but the panel was hidden prior to the extension running

That said, if your workflow is such that you basically always have have a terminal open, @MykhailoSukhostavets' will be very useful :) Happy holidays!
