### ISSUE TITLE
Publish to open-vsx

### ISSUE THREAD

**Issue by maxim092001** [tomrijndorp/vscode-finditfaster#42]
Hey!

Some of the tools are using [open-vsx](https://open-vsx.org/) to automatically install extensions in remote containers.

Can we publish find-it-faster there? Thanks!

**Comment by tomrijndorp** [comment]
Hi, thanks for the suggestion. I had a look but I have trouble understanding the value proposition; my initial thoughts are that I don't think I'm interested in creating more accounts and keeping these in sync. I've never heard of anyone having a single issue with VS Code marketplace :)

**Comment by jounathaen** [comment]
Ok, then I'll be the one. I use VSCodium (not a fan of getting tracked by MS) and VSCodium has no direct access to the VS Code marketplace and uses Open VSX instead.
It is possible to download the vsx from MS website and install it manually, but then you don't get any updates.

**Comment by tomrijndorp** [comment]
Alright, that makes sense! The extension is now also published on OpenVSX and should be automatically updated when new releases are created.
