### ISSUE TITLE
Resume search (also called "repeat search")

### ISSUE THREAD

**Issue by alexrenz** [tomrijndorp/vscode-finditfaster#43]
Hi! I recently switched from Emacs to VSCode and absolutely love this extension 💛 Thank you so much for developing this!

I found that I am missing one feature that I used to use a lot: resume search (often also called "repeat search"). That means: I search for a term with `find_within_files`, open one candidate in the editor to edit something (thus closing the search terminal), and then resume the search to visit other candidates. This exists as `ivy-resume`, `vertico-repeat`, `selectrum-repeat` in the Emacs world. At least one of my colleagues is also missing this functionality.

I looked around the extension a bit and it seems that this is not directly supported. Or am I missing something?

I thought about + searched for potential workarounds/alternatives:
1. I found this: https://github.com/tomrijndorp/vscode-finditfaster/discussions/27 (using tab to select multiple files + open them together). However, this seems to not work for me, so I wasn't able to try this yet. But this wouldn't directly support my preferred workflow.
2. One could potentially keep the search window open while making edits in the editor. This does not work well for me because the keyboard shortctus that I use to move around vscode don't work in the terminal (i.e., I have no way to conveniently switch out of the terminal and back into it). But maybe with some good shortcuts this might be tenable.

How do you feel about a resume/repeat functionality? I.e., a separate key binding for resuming the last search. A nice to have would be to have it jump back to the candidate that was marked when the search was last exited, but even a resume functionality without that would be extremely helpful for me.

I am willing to implement this if you are generally interested. One approach would be to write the current query to a "last query" file when a search is exited, and restore this query when a newly introduced "repeat query" action is invoked. An alternative approach would be to record query history more generally in a history file and allow the user to cycle through the last queries. Other ideas?

Again, I absolutely love this extension, and would love to help make it a tiny bit better for me and maybe a few others :)

**Comment by tomrijndorp** [comment]
Thanks for the kind words! This has now been requested a couple times (also #34 which I closed for no good reason apparently) so I'm inclined to get this to work. I think storing the last query in a temp file is probably the way to go, and If you're willing to give it a stab I'm all for it. I think I would prefer:
- Indeed this should be a separate command
- I'd prefer not having an assigned default key binding
- works on both Windows and Unix, or at least an error on the other platform using e.g. `vscode.window.showErrorMessage`
- consider how this interacts with `find within files (using type filter)`. It's pretty much exactly the same code path so I think it should just work

If you don't have cycles to look into this after all I'll give it a try myself at some point :)

**Comment by alexrenz** [comment]
Lovely! I will give this a go next week and see how far I get :)
