### ISSUE TITLE
Using `/usr/bin/env bash` instead of `/bin/bash`

### ISSUE THREAD

**Issue by ShaolunWang** [tomrijndorp/vscode-finditfaster#44]
Currently `/bin/bash` is used in all the bash scripts. This would break on systems like NixOS which doesn not have `/bin/bash` because of its non standard file system. Is it possible to change it to `/usr/bin/env bash` instead?

**Comment by tomrijndorp** [comment]
Thanks for the suggestion. While I think this should generally work, there are some [concerns](https://unix.stackexchange.com/a/238470/128132) around using this construct that I think are valid. Furthermore, with thousands of installs a change like this might break the extension in other people's environments, so I'm reluctant to implement this change at this point. I'd recommend to - if you have the permissions on this system - symlink your bash binary to `/usr/bin/bash` to address this.

**Comment by qingbyin** [comment]
Hi,  
This issue can be easily resolved on NixOS by enabling `services.envfs`. This setting ensures that paths like `/bin/bash` are correctly mapped. 

To enable it, simply add the following to your NixOS configuration and rebuild:  

```nix
services.envfs.enable = true;
```
