### ISSUE TITLE
Search window closes if settings.json is changed.

### ISSUE THREAD

**Issue by hakan-demirli** [tomrijndorp/vscode-finditfaster#47]
**How to reproduce:**
1- Open settings.json in an editor (vscode, neovim, notepad ...).
2- Open vscode (code) and start fuzzy search Ctrl+Shift+j. Don't press enter let it wait.
3- Edit settings.json:
```json
    "editor.cursorStyle": "block", ->     "editor.cursorStyle": "line", 
```
4- Save settings.json

In vscode suddenly fuzzy search terminates and terminal closes.

**Comment by tomrijndorp** [comment]
Hi, I can confirm. This is intended behavior. Some workspace settings affect the extension's behavior, in some cases requiring the extension to be restarted.

**Comment by hakan-demirli** [comment]
I see. Thank you for the quick response.
