### ISSUE TITLE
feat-request: add a bool option to be able to kill terminal session after executing a command

### ISSUE THREAD

**Issue by ruslanSorokin** [tomrijndorp/vscode-finditfaster#49]
First of all, thank you so much for this extension. I've been using it literally every day since I found it on the marketplace.

# Proposal
Add a boolean option `"find-it-faster.general.killTerminalAfterUse"` It may be implemented the same way as `"find-it-faster.general.clearTerminalAfterUse"` 

### Behavior
If this option is set to `true`, then after each use allocated terminal will be killed. It probably adds some performance penalties, since it creates a new terminal instance per call to the extension, but I didn't find these penalties to be even remotely meaningful, when I've been doing the same manually all the time.

# Why
I'm using integrated terminal for compilation/linting/testing/commiting and etc. So, I always have one active instance. 
But after call to the extension, it's terminal becomes active, pushing previously active instance into the background. I'm forced to manually kill this new instance or switch back to previously active one. With this option, allocated for extension instance won't push previously active instance into the background.

**Comment by tomrijndorp** [comment]
Thanks for the suggestion and the detailed description! It makes sense -- it's unfortunate VS Code doesn't enable better programmatic access to the terminal so I don't have much control. But this I'm pretty sure I can do. If your system is anything like mine the performance degradation will be noticeable, but no harm in adding it; should be straightforward :)

**Comment by tomrijndorp** [comment]
This is now in the latest release (`0.0.26`)!

**Comment by ruslanSorokin** [comment]
Oh, thanks a lot. I've just check it out. It works just the way I wanted.

**Comment by tomrijndorp** [comment]
Great!
