### ISSUE TITLE
Default fzf --height to 100% or allow setting it

### ISSUE THREAD

**Issue by timkgh** [tomrijndorp/vscode-finditfaster#50]
I think it makes sense for fzf to take up the entire terminal window in this case, so I think it should just default `--height='100%'` or if that doesn't seem like a good default, could you please add a setting for it? Maybe a general setting where the user can override any `fzf` defaults.

**Comment by tomrijndorp** [comment]
Hi, I'm not sure if I understand? If I maximize the terminal panel, FZF takes up all space for me. And the extension has a setting to maximize the terminal panel by default. Maybe you can clarify how what you're asking for is different? Thanks :)

<img width="2048" alt="Screenshot 2023-09-23 at 16 40 44" src="https://github.com/tomrijndorp/vscode-finditfaster/assets/15803419/dc7a1253-199c-42fb-a452-c0817abf4289">

**Comment by timkgh** [comment]
Ah, right. Becuase I have `--height=50%` in `FZF_DEFAULT_OPTS` I'd like to reset it to 100% for FindItFaster, without resetting it in general for other terminals I use in VS Code.

**Comment by tomrijndorp** [comment]
I just had a look to see if there's a way in which you can already do this, and I think the more flexible way to approach this for you is to edit your environment `rc` file:
```bash
if [[ $TERM_PROGRAM == vscode ]]; then  # vscode sets this in its terminal environments
    FZF_DEFAULT_OPTS='--height=100%'
else
    FZF_DEFAULT_OPTS='--height=50%'
fi
```

**Comment by timkgh** [comment]
Thanks for the suggestion, but it doesn't work for _all_ terminals that one might use in VS Code, for other purposes where 50% height may be a better choice. Is it possible for the extension to allow setting `FZF_DEFAULT_OPTS`(or some other field that can override fzf options), with the understanding that it is an advanced option that may break the extension's behavior?

Or an alternative that might work in this case though less flexible for other settings might be a check box "Ignore FZF_DEFAULT_OPTS from env".

**Comment by tomrijndorp** [comment]
You can also apply this only to the extension using your rc file; you can check whether `FIND_FILES_PREVIEW_COMMAND` is set to determine whether you're running FZF inside the extension or outside :)

**Comment by timkgh** [comment]
Thanks, this works. Could you please document it so it's easier for others to discover? Or better yet, rather than using the not so obvious `FIND_FILES_PREVIEW_COMMAND` env var, maybe introduce a more generic `FINDITFASTER_ACTIVE=true` env var?

**Comment by tomrijndorp** [comment]
Agreed, will do those things on the next release :+1:

**Comment by tomrijndorp** [comment]
`FIND_IT_FASTER_ACTIVE` will be set in extension version 0.0.27 and above. Thanks for the suggestion!

**Comment by timkgh** [comment]
Is it `FIND_FIND_IT_FASTER_ACTIVE` according to the release notes?

**Comment by tomrijndorp** [comment]
Yes

**Comment by timkgh** [comment]
Please see my comment here
https://github.com/tomrijndorp/vscode-finditfaster/commit/f5d90a1d11330ce5b8ff7362f0040d1de8da8165#r129252567
