### ISSUE TITLE
@ in directory name causing issues

### ISSUE THREAD

**Issue by md1440** [tomrijndorp/vscode-finditfaster#51]
Hi,

I happen to be working in a directory starting with @dir, which seems to be causing an issue when trying to use FindItFaster:

`::: Terminal allocated for FindItFaster. Do not use. ::: /home/marc/.vscode/extensions/tomrijndorp.find-it-faster-0.0.26/find_within_files.sh  '/home/marc/Documents/%40WebDev/test'
/home/marc/.vscode/extensions/tomrijndorp.find-it-faster-0.0.26/find_within_files.sh: line 12: cd: /home/marc/Documents/%40WebDev/test: No such file or directory`

It works without issues in dirs not containing @

**Comment by tomrijndorp** [comment]
What system are you running on? I can't reproduce this on Ubuntu 20.04.

**Comment by md1440** [comment]
Interesting! I am running Fedora 38. Anything else I can support you with?

**Comment by tomrijndorp** [comment]
That is interesting. This is the annoying thing about an extension that relies so heavily on dependencies over which I have no control. This may be related to the bash version in your distro, and/or some interaction with the extension. Anyone's guess at this point. It's pretty obscure. I'll leave this open and hope that somebody who can reproduce this issue has an appetite to fix it...

**Comment by tomrijndorp** [comment]
Hopefully this is now resolved as of version 0.0.33 (thanks @numanhg!)
