### ISSUE TITLE
0.0.27 breaks the flight check

### ISSUE THREAD

**Issue by UberMouse** [tomrijndorp/vscode-finditfaster#54]
As per title, when the extension updated to 0.0.27 the flight check now fails. It says it's unable to find `rg` on my PATH. Reverting back to 0.0.26 and the problem goes away.

**Comment by UberMouse** [comment]
Nope I've definitely got `sed` on my PATH. Not sure if there is a way for me to see the output of the flightcheck.sh script when it runs to provide you with more info

**Comment by tomrijndorp** [comment]
Apologies. This is now fixed in `0.0.28` which should appear in the marketplace any minute.
