### ISSUE TITLE
How to get this working in a devcontainer?

### ISSUE THREAD

**Issue by Andrei2Moraru** [tomrijndorp/vscode-finditfaster#57]
Thanks for making this! Works nice locally, but I got into trouble making this work in a devcontainer because of `bat`

Using something like:

```json
 "postCreateCommand": "sudo apt-get update && sudo apt-get install -y bat fzf ripgrep",
```

in the `devcontainer.json` will not work, although it does make `bat` usable as a cli tool.

Making the symbolic link also does not help here:

```json
  "postCreateCommand": "sudo apt-get update && sudo apt-get install -y bat fzf ripgrep && mkdir -p ~/.local/bin && ln -s /usr/bin/batcat ~/.local/bin/bat"
```

This [wsl fix](https://github.com/tomrijndorp/vscode-finditfaster/issues/28) also did not do it for me.

The error is always: `Failed to active the plugin , bat not found on your PATH`.

Any ideas?

**Comment by tomrijndorp** [comment]
I have zero experience with devcontainers so I can't contribute much here. I think it'd be good to know that the extension really just runs in a fairly vanilla terminal within VS Code, so if you can figure out more about that environment (e.g. `PATH`, etc.) you might be able to figure out why it's not working.

Also, here's a post I've linked in related issues before regarding how to set additional env vars: https://stackoverflow.com/a/45637716/888916, that should help correct any e.g. `PATH` issues to help get things running.

Hope this helps!
