### ISSUE TITLE
How to resize the preview window

### ISSUE THREAD

**Issue by xxd-0524** [tomrijndorp/vscode-finditfaster#6]

**Comment by tomrijndorp** [comment]
This can be done in the extension settings.

_For the "Find Files" option:_
<img width="1118" alt="Screen Shot 2021-07-06 at 21 37 30" src="https://user-images.githubusercontent.com/15803419/124701192-fe73c400-dea2-11eb-87f1-56bddc071e52.png">

_For the "Find Within Files" option:_
<img width="1118" alt="Screen Shot 2021-07-06 at 21 39 28" src="https://user-images.githubusercontent.com/15803419/124701197-00d61e00-dea3-11eb-8381-ea4fef554aa6.png">

Hope this helps!
