### ISSUE TITLE
find_files.ps1 instantly closes on Find It Faster: search file

### ISSUE THREAD

**Issue by Granshmeyr** [tomrijndorp/vscode-finditfaster#67]
The script exits immediately after the terminal opens with the following error:

    → C:\Users\Grindle\Documents\Other\Godot\Projects\Fish-Game [main ≡ +4 ~5 -0 !]› c:\Users\Grindle\.vscode\extensions\tomrijndorp.find-it-faster-0.0.30\find_files.ps1  'c:\Users\Grindle\Documents\Other\Godot\Projects\Fish-Game'
    unknown option: 
    canceled
    → C:\Users\Grindle\Documents\Other\Godot\Projects\Fish-Game [main ≡ +4 ~5 -0 !]› 

For some reason `$QUERYPARAM =  ""` is parsed as an actual parameter, hence `unknown option:`.

I've never used PowerShell before but here is an inelegant solution that constructs the command in a more explicit fashion:

Replace

    if ($PREVIEW_ENABLED -eq 1) {
        $result = Invoke-Expression "rg --files --hidden $USE_GITIGNORE_OPT --glob '!**/.git/' $GLOBS $TYPE_FILTER_ARR $PATHS" | fzf --cycle --multi $QUERYPARAM "${QUERY}"  --preview "$PREVIEW_COMMAND" --preview-window "$PREVIEW_WINDOW"
    }
    else {
        $result = Invoke-Expression "rg --files --hidden $USE_GITIGNORE_OPT --glob '!**/.git/' $GLOBS $TYPE_FILTER_ARR $PATHS" | fzf --cycle --multi "$QUERYPARAM" "${QUERY}"
    }

With

      $fzf_array = @("fzf", "--cycle", "--multi")
      if ($QUERYPARAM -ne "") {
          $fzf_array += $QUERYPARAM
          $fzf_array += "${QUERY}"
      }
      if ($PREVIEW_ENABLED -eq 1) {
          $fzf_array += "--preview"
          $fzf_array += "'$PREVIEW_COMMAND'"
          $fzf_array += "--preview-window"
          $fzf_array += "$PREVIEW_WINDOW"
      }
      $fzf_command = $fzf_array -join " "
    
      $rg_array = @("rg", "--files", "--hidden", "--glob", '!**/.git/')
      if ((VGet "env:USE_GITIGNORE" 0) -eq 0) {
          $rg_array += "--no-ignore"
      }
      if (($GLOBS.Length -gt 0)) {
          $rg_array += "$GLOBS"
      }
      if (($TYPE_FILTER_ARR.Length -gt 0)) {
          $rg_array += "$TYPE_FILTER_ARR"
      }
      if (($PATHS -ne "")) {
         $rg_array += "$PATHS"
      }
      $rg_command = $rg_array -join " "
    
      $result = Invoke-Expression ($rg_command + " | " + $fzf_command)

EDIT: Note there is already an old, now-closed pull request that tried to solve this problem but it didn't really solve it and more so hacked it out; see https://github.com/tomrijndorp/vscode-finditfaster/pull/30

EDIT 2: This seems to also be an issue in the other scripts.

**Comment by vmasrani** [comment]
Having the same problem

**Comment by tomrijndorp** [comment]
I personally can't help with this as I don't own a Windows machine, and rely on community contributions for the experimental Windows support. So I'm leaving this open and hopefully it'll be picked up at some point :)

**Comment by sainsay** [comment]
#71 has some proposed changes as a fix for this issue. Please let me know if changes are required.

**Comment by Luiggi33** [comment]
@tomrijndorp would it be possible to merge that PR to fix this issue?

**Comment by acbach** [comment]
Tried out the changed locally on my windows machine. This fixed the instant close for me.

**Comment by tomrijndorp** [comment]
Apologies, I haven't been able to focus much on this extension lately due to other commitments. I just published version 0.0.31 which incorporates @Luiggi33's PR :)
