### ISSUE TITLE
`search within files` doesn't actually search

### ISSUE THREAD

**Issue by dariooddenino** [tomrijndorp/vscode-finditfaster#8]
Hi!
I'm on ubuntu 20.04, vscode is at 1.60.1 and finditfaster at 0.0.13.

I have all the dependencies installed, and `search file` works fine.

The problem is with `search within files`.  
No matter what I type, the number of matches doesn't change. I can see the matches list change a little, but nothing related to my actual search comes up. It almost look like it's doing some random reordering of the list.

Thank you for writing the extension! I was about to write one myself because I really hate the sidebar :D

**Comment by tomrijndorp** [comment]
Hi @dariooddenino, thanks for reporting, and glad you like the extension! Apologies for the late response. This one might be hard to track down. I've only seen something similar when searching _very_ large numbers of files, in which case it takes `rg` forever to index. Some ideas to narrow this down:

1. Can you maybe run `Find It Faster: list search locations` and see if that shows something obvious like `/` being in there? 
3. What does `rg --version` return for you?
2. Maybe a screengrab would be helpful.

Other than that I don't have any ideas as to what this could possibly be.

**Comment by dariooddenino** [comment]
Hi! Thanks for the answer!

1. `list search locations` shows the project folder only, so it looks ok.
![listfiles](https://user-images.githubusercontent.com/3266789/134636363-c1cd706c-8abb-46a0-8579-484deee96b6a.png)

2.  `rg --version` returns:
```
ripgrep 11.0.2
-SIMD -AVX (compiled)
+SIMD +AVX (runtime)
```
3. Attaching a couple of screenshots of me trying to use it on this repo. The first is without anything typed in, the second is after I typed something. I can see the loading thing for an instant, but as you can see there's no difference in the results list. Is it normal that it's showing every single line of every file?
![emptysearch](https://user-images.githubusercontent.com/3266789/134636815-70d0f448-9c50-48fa-acca-bf6f8488609d.png)
![search](https://user-images.githubusercontent.com/3266789/134636825-adae767c-3584-4fd1-b6af-0445bf540df2.png)

**Comment by tomrijndorp** [comment]
Ah, very clever to try it on this repo, I happen to have that code!

Unfortunately, I'm clueless at this point. Especially given that `search within files with type` _is_ working for you. I just double checked, and there's literally only a single difference between those two code paths (after making a selection), which is to add `--type <filetype>` to the `rg` invocation. I also tried to reproduce your step 3) and it works correctly for me (searching for my name should narrow the results down to two lines).

I'm going to leave the ticket open, if at any point you find another bit of information that could point me in the right direction to track this down I'd really appreciate it!

**Comment by dariooddenino** [comment]
After some tests I found that the culprit is https://github.com/tomrijndorp/vscode-finditfaster/blob/main/find_within_files.sh#L31

Removing that line makes the standard `search within files` work for me. I guess it makes the `with type` version pointless, but I can live with that.

This is the command output with that line:
```bash
rg --column --hidden --line-number --no-heading --color=always --smart-case --colors 'match:fg:green' --colors 'path:fg:white' --colors 'path:style:nobold' --glob '!**/.git/' '--glob' '!**/node_modules' '--glob' '!**/bower_components' '--glob' '!**/*.code-search' '--glob' '!**/.github' '--glob' '!**/.vscode' '--glob' '!**/*.svg' '--glob' '!**/package-lock.json' '' 2> /dev/null
```

And this is the output without it:
```bash
rg --column --hidden --line-number --no-heading --color=always --smart-case --colors 'match:fg:green' --colors 'path:fg:white' --colors 'path:style:nobold' --glob '!**/.git/' '--glob' '!**/node_modules' '--glob' '!**/bower_components' '--glob' '!**/*.code-search' '--glob' '!**/.github' '--glob' '!**/.vscode' '--glob' '!**/*.svg' '--glob' '!**/package-lock.json' 2> /dev/null
```

There's an extra `''` in the first version, which I think is what is causing the command to always return every file from my work directory.
I'm going to install this "fix" locally, but maybe this is still helpful for you!

**Comment by tomrijndorp** [comment]
This is super helpful, thanks so much! I think this might come down to the bash version used. I'm doing most of my testing on MacOS, which has bash 3.2.57. With this information, I think I'll probably be able to reproduce on my Linux box. I'll update the ticket to let you know when there is a new version ready so you can try it out!

**Comment by tomrijndorp** [comment]
Alright, this took a while, but I managed to reproduce (only on Linux, fortunately) and create a fix. If you update to 0.0.14 which should now be available, things should work as expected, but please let me know if it doesn't.

Thanks again for reporting _and_ digging into it!

**Comment by dariooddenino** [comment]
It works perfectly now, thanks!
