### ISSUE TITLE
Preserve cursor position

### ISSUE THREAD

**Issue by jamesnolanverran** [tomrijndorp/vscode-finditfaster#81]
I have a small feature request. Normally in VSCode If you open a file, the editor remembers where your cursor was the last time it was open. Whereas if I open a file using finditfaster my cursor always lands at the top of the document, even if the file was already open.

Thanks, and thanks for the great plugin.

James

**Comment by tomrijndorp** [comment]
Thanks for catching and reporting that! This was a small bug that I somehow never noticed myself. It's fixed in version `0.0.32` which is being released now.
