### ISSUE TITLE
Windows Failed Flight_Check.ps1 when user account has a whitespace character

### ISSUE THREAD

**Issue by DarksideVT** [tomrijndorp/vscode-finditfaster#88]
# Issue
Cannot run `find it faster` extension and I receive an error.

# Steps to Reproduce
When your user account directory has a white space character, an error occurs suggesting the file path was not found

# Example
If your account directory is `C:\Users\Arthur Edmiston\.vscode\extensions\tomrijndorp.find-it-faster-0.0.33\`, there is an error because it tries to find files in `C:\Users\Arthur`

# Solution
I'm not familiar enough with js or powershell to know where the directory is determined but I suspect if you put it in quotes of some sort, it'll fix the directory issue I'm having.

**Comment by Luiggi33** [comment]
What exactly are you trying to do and could you put the whole error message in here?

**Comment by DarksideVT** [comment]
When I try to run the hotkeys it comes up with an error

```
Failed to run checks before starting extension. Maybe this is helpful: Error: Command failed: powershell c:\Users\Arthur Edmiston\.vscode\extensions\tomrijndorp.find-it-faster-0.0.33\flight_check.ps1
c:\Users\Arthur : The term 'c:\Users\Arthur' is not recognized as the name of a cmdlet, function, script file, or 
operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try 
again.
At line:1 char:1
+ c:\Users\Arthur Edmiston\.vscode\extensions\tomrijndorp.find-it-faste ...
+ ~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (c:\Users\Arthur:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
 
```

**Comment by DarksideVT** [comment]
What is the best way for me to test this? I'd be happy to if needed.

**Comment by Luiggi33** [comment]
Okay, either you [download](https://github.com/Luiggi33/vscode-finditfaster/archive/refs/heads/patch-flightcheck.zip) and compile it yourself with `npm install` and `npm run vscode:package`.
I also [compiled it myself](https://workupload.com/file/7FnjvES24fL), but you should never trust randoms online.

**Comment by DarksideVT** [comment]
Finally figured out how to build this.

Getting this error
```
c:\Users\Arthur : The term 'c:\Users\Arthur' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ c:\Users\Arthur Edmiston\.vscode\extensions\tomrijndorp.find-it-faste ...
+ ~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (c:\Users\Arthur:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
  ```
  
  Seems like this didn't fix my particular issue.

**Comment by DarksideVT** [comment]
I built the latest from main and can confirm I have the changes you made to the extension. I also uninstalled and installed version 0.0.34 from the Marketplace. Same error occurs.

**Comment by RayanSaeed** [comment]
Why was this issue closed? It doesn't seem to be resolved yet

**Comment by Cryxto** [comment]
it still not fixed
