### ISSUE TITLE
Can't manage to get the extension running in VSCode with WSL2

### ISSUE THREAD

**Issue by Jaizu** [tomrijndorp/vscode-finditfaster#89]
I'm pretty sure that opening a github issue is not the proper way to get support but I'm trying to run this extension inside of VSCode using WSL2 with latest Ubuntu with no luck, I made sure that I installed all the requirements in my ubuntu wsl and even made an alias in zsh so bat is batcat. I sourced my zsh config and made sure it updated. batcat works from the terminal.
When I try to pres control + shift + j I get the following message:
```
Failed to activate plugin: bat not found on your PATH
. 
Make sure you have the required command line tools installed as outlined in the README.
```
Is it trying to read my windows terminal or something like that? If so, why is that the case if I'm running VSCode withing a WSL folder and the plugin is installed in my WSL.
![image](https://github.com/tomrijndorp/vscode-finditfaster/assets/18596778/d6938100-a97c-43a7-958a-1ff9c3dc8bb3)

If there is a Discord for this extension I'm more than happy to join and ask for support there.

**Comment by Luiggi33** [comment]
I can replicate this, seems to be related to the renaming of bat to batcat and the supplied fix, at least thats my first guess

**Comment by Jaizu** [comment]
I only renamed it because it didnt get it by default, I googled and it said that bat is ran as batcat in ubuntu, so I added an alias for it

**Comment by Luiggi33** [comment]
@Jaizu Can you please run `which bat` in the Ubuntu console and send the result of that in here?

**Comment by Jaizu** [comment]
~/decomp/recharged-yellow master !7 ?2 ❯ which bat                                                                                                                                                                                                                                         13:43:04
bat: aliased to batcat
~/decomp/recharged-yellow master !7 ?2 ❯ which batcat                                                                                                                                                                                                                                      13:51:15
/usr/bin/batcat

**Comment by Luiggi33** [comment]
That seems to fuck it up, can you try installing bat via the .deb file in the release?
For this you first need to comment out your alias, then download the newest bat release via wget (or whatever else you wanna use) `wget https://github.com/sharkdp/bat/releases/download/v0.24.0/bat-musl_0.24.0_amd64.deb`, then install it `sudo dpkg -i bat-musl_0.24.0_amd64.deb`

**Comment by Luiggi33** [comment]
Just as a quick info, I tried it on my own WSL installation and using the .deb file, everything worked.
This is more of a temporary workaround tho

**Comment by Jaizu** [comment]
Hi, installing the .deb one worked. I didn't have an alias when I tried this the first time, I only added it because WSL couldn't run bat and only batcat after doing sudo apt-get install bat

**Comment by Luiggi33** [comment]
Because I am sadly not a big linux user, I did more digging. The preflight check script runs doesnt run in your "session", so it doesn't load the alias's from the `.bashrc`

**Comment by vmasrani** [comment]
I was getting similar issues ("fzf not found on your PATH") despite having fzf on the path. Simple fix was settings ->Find-it-faster -> Disable Startup Checks

**Comment by Luiggi33** [comment]
@Jaizu Do you still have this issue or could you close it maybe?

**Comment by Antardas** [comment]
> sudo dpkg -i bat-musl_0.24.0_amd64.deb

it's worked in ubuntu also
