### ISSUE TITLE
Possible to use without VS Code?

### ISSUE THREAD

**Issue by sebbi08** [tomrijndorp/vscode-finditfaster#95]
Would it be possible to start the searches without VS Code in a plain terminal ?

**Comment by christianallred-nomi** [comment]
fzf, bat, rg ? 
i know its not as pretty, but i think this is outside the scope of what is trying to be accomplished by this code base

**Comment by sebbi08** [comment]
Ah ok i see, yea than i will take a look and write myself a small script :)
